# k-nearest neighbors classification
Import libraries:

In [5]:
import itertools
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.ticker import NullFormatter
import pandas as pd
import numpy as np
import matplotlib.ticker as ticker

from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics

Prerare the dataset:

In [6]:
#https://www.kaggle.com/cclayford/statbunker-football-stats?select=Player+Stats+2019-20.csv

df_raw = pd.read_csv("data/players_stats_1920.csv")
df = df_raw.loc[(df_raw['Type Of Goal'] == 'Player'), ['Player','Position','Appearances','Started','Started As A Sub','Goals','Assists','Yellow Cards']]
df[['Appearances','Started','Started As A Sub','Goals','Assists','Yellow Cards']] = df[['Appearances','Started','Started As A Sub','Goals','Assists','Yellow Cards']].astype(int)
df = df[df['Appearances']>5]

x = df[['Appearances','Started','Started As A Sub','Goals','Assists','Yellow Cards']].values  #.astype(float)
y = df['Position'].values

x = preprocessing.StandardScaler().fit(x).transform(x.astype(float))
print(x[0:10])

x_train, x_test, y_train, y_test = train_test_split( x, y, test_size=0.2, random_state=4)
print ('Train set:', x_train.shape,  y_train.shape)
print ('Test set:', x_test.shape,  y_test.shape)

[[ 1.87870959  2.00343641 -1.14144832  0.93114306 -0.27953993 -0.65518798]
 [ 1.87870959  1.85244015 -0.95509121  0.16030267  6.17679264  0.78654429]
 [ 1.87870959  1.85244015 -0.95509121 -0.22511753  3.59425961 -0.65518798]
 [ 1.87870959  1.70144389 -0.76873411  2.47282384  4.23989287 -1.13576541]
 [ 1.69576116  1.85244015 -1.14144832  0.16030267 -0.27953993 -1.13576541]
 [ 1.69576116  1.39945137 -0.39601989  0.54572286  2.94862635 -0.65518798]
 [ 1.32986431  1.55044763 -0.76873411  4.78534502  3.59425961 -0.65518798]
 [ 1.32986431  1.24845511 -0.582377    4.01450463  3.59425961 -0.17461056]
 [ 0.78101904 -1.16748506  2.58569384  0.54572286 -0.27953993 -1.13576541]
 [ 0.41512219  0.79546633 -1.14144832 -0.61053772 -0.27953993 -1.13576541]]
Train set: (1688, 6) (1688,)
Test set: (423, 6) (423,)


Train Model and Predict

In [7]:
k = 15
neigh = KNeighborsClassifier(n_neighbors = k).fit(x_train,y_train)

print(neigh)

yhat = neigh.predict(x_test)
yhat[0:10]

print("Train set Accuracy: ", metrics.accuracy_score(y_train, neigh.predict(x_train)))
print("Test set Accuracy: ", metrics.accuracy_score(y_test, yhat))


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=15, p=2,
                     weights='uniform')
Train set Accuracy:  0.6030805687203792
Test set Accuracy:  0.4988179669030733
